[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

# Handle API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# For client-side routing - this must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200