[build]
  command = "npm run build"
  publish = "dist/public"

# Add API proxy for Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# For client-side routing (must be after the API redirect)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200